name: matlab
channels:
  - anaconda
  - conda-forge
dependencies:
  - cffi=1.12.3
  - openmp=8.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - matplotlib=3.1.1
  - notebook=6.0.0
  - ipywidgets=7.5.1
  - numba=0.45.1
  - numpy=1.17.0
  - panel=0.6.0
  - python=3.7.3
  - scipy=1.3.0
  - seaborn=0.9.0
